const expr=require('express')
const app=expr()
const bp=require('body-parser')
const adminsrout=require('./routes/admin')
const shopr=require('./routes/Shop')
app.use(bp.urlencoded())
app.use(shopr)
app.use(adminsrout)

app.listen(3000)
